# http://travis-ci.org/#!/agschwender/pilbox
language: python
python:
  - 2.6
  - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"
  - 3.3
env:
  - PYTHONPATH=$PYTHONPATH:$PWD
before_install:
  - sudo apt-get install libjpeg8-dev libfreetype6-dev zlib1g-dev
  - sudo apt-get install libwebp-dev liblcms2-dev
#  - sudo apt-get install python-numpy python-opencv
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - pip install --use-mirrors tornado==3.2.1 Pillow==2.4.0 coveralls
  - pip install --use-mirrors pep8==1.4.6 pyflakes==0.7.3
before_script:
  - pep8 --exclude=test pilbox
  - pyflakes pilbox/*.py
script:
  - coverage run -m pilbox.test.runtests
after_success:
  - coveralls
